-- EQUILIBRADO
INSERT INTO Producto (nombre, descripcion, precio, stock, tipo, imagen_url) VALUES
('Ensalada de Pavo y Pina','1 lechuga. 200 gramos de pechuga de pavo asada. 200 gramos de queso feta. 90 gramos de cebollitas encurtidas. 1 lata de maíz dulce. 6 rodajas de piña, con su jugo. 1 zanahoria', 10.5, 1, 'Equilibrado', '../static/img/ensaladaPavoPina.jpg'),
('Pasta carbonara','400 g de spaghetti Garofalo. 200 g de panceta curada de cerdo. 50 g de queso Parmigiano Reggiano. 3 yemas y 1 huevo entero', 9.8, 80, 'Equilibrado', '../static/img/pastacarbonara.jpg'),
('Guisantes con Jamon y Sepia','3 dientes de ajo. 50 g de aceite de oliva. 300 g de sepia limpia. 90 - 100 g de jamón curado en dados. 100 g de vino blanco. 500 g de guisantes congelados', 11.2, 60, 'Equilibrado', '../static/img/guisantesconjamonysepia.jpg'),
('Calabacines rellenos','4 calabacines medianos. 2 cebollas. 1 diente de ajo. 300 ml de bechamel. 100 g de queso rallado para gratinar', 8.9, 90, 'Equilibrado', '../static/img/calabacinesrellenos.jpg'),
('Arroz tres delicias','400 g de arroz. 1 zanahoria. 75 g de gambas. 75 g de guisantes. 75 g de jamon york. 20 ml de salsa de soja. 2 huevos.', 9.3, 70, 'Equilibrado', '../static/img/arroztresdelicias.jpg'),
('Potaje de Garbanzos con Espinacas','200g de garbanzos frescos. 2 cebolletas. 1 hoja de laurel. 1 manojo de espinaca fresca. Sal y aceite de oliva virgen extra.', 8.7, 75, 'Vegano', '../static/img/potajedegarbanzosconespinacas.jpg'),
('Ratatouille','350 g de Tomate frito. 300 g de calabacín. 550 g de berenjena. 600 g de tomate. 200 g de cebolla. 5 dientes de ajo. Orégano al gusto. Sal y dos cucharadas de aceite de oliva', 9.5, 90, 'Vegano', '../static/img/ratatouille.jpg'),
('Arroz con Verduras','4 dientes de ajo. 1 tomate. 100 gramos de arroz integral. 1 cucharadita de pimenton dulce. Agua y aceite de oliva virgen extra.', 7.9, 100, 'Vegano', '../static/img/arrozconverduras.jpg'),
('Tortilla vegana de Calabacin','60 g de harina de garbanzos. 1 calabacín grande. 1/4 cucharadita de sal. 1 cucharadita de cúrcuma molida. 120 ml de agua. Aceite de oliva virgen extra.', 6.5, 110, 'Vegano', '../static/img/tortillaveganadecalabacin.jpg'),
('Dahl de Lentejas rojas y Boniato','200 gr de lentejas rojas. 300 gr de boniato. 1 litro de caldo de verduras. 1 cebolla. 2 dientes de ajo. 2 cucharadas de aceite de oliva virgen extra.', 8.2, 85, 'Vegano', '../static/img/dahldelentejasrojasyboniato.jpg'),
('Alubias con almejas','400 g de alubia blanca redonda. 400 g de almejas. Media cebolla. 4 dientes de ajo. Un trozo de pimiento rojo y otro verde. Una hoja de laurel. Un puerro. Sal, pimienta y perejil picado', 12.5, 70, 'Proteico', '../static/img/alubiasconalmejas.jpg'),
('Garbanzos con Espinacas y Bacalao','200 g de garbanzos frescos. 200 g de bacalao. 500 ml de caldo de pescado. 150 g de espinaca fresca o congelada. 1 huevo cocido. 2 dientes de ajo.', 11.3, 90, 'Proteico', '../static/img/garbanzosespinacasbacalao.jpg'),
('Lentejas con Pollo y Manzana','200 g de lentejas. 250 g de pechuga de pollo. 150 g de manzana. 100g de cebolla. Agua y aceite de oliva virgen extra', 10.9, 60, 'Proteico', '../static/img/lentejaspollomanzana.jpg'),
('Estofado de Ternera','500g de ternera. 1 cebolla. 1 zanahoria. 1 diente de ajo. 250 g de caldo de carne. Sal y pimienta al gusto.', 13.0, 55, 'Proteico', '../static/img/estofadodeternera.jpg'),
('Tortilla de patatas vegana','400 g de patata. 150 g de cebolla. 70 g de harina de garbanzos. 180 ml de agua. Aceite de oliva virgen extra y sal.', 9.2, 100, 'Proteico', '../static/img/tortillavegana.jpg');
